"""empty message

Revision ID: 6c5bb05b8d1c
Revises: 8bb1ff11e2fe
Create Date: 2022-10-26 20:06:34.114959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5bb05b8d1c'
down_revision = '8bb1ff11e2fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subject', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subject', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subject', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subject', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
